In [257]:
import pandas as pd

In [258]:
ovr = pd.read_csv('OVR_data.csv')

In [259]:
ovr.head(5)

,Unnamed: 0,Player,Season,Born,Age,Squad,Nation,Previous Market Value,Market Value,Position,...,Interceptions,Fouls,Last man,Tackles,ELG,OwnGoal,Clears,ABW,ABL,OVR(%)
0,0,Éder,2015-2016,1987,27,Swansea City,Portugal,5500000,4500000,FW,...,0,11,0,4,0,0,7,9,20,3.0
1,1,Álvaro Morata,2017-2018,1992,25,Chelsea,Spain,44000000,58500000,FW,...,6,41,0,13,0,0,20,54,59,36.9
2,2,Álvaro Morata,2018-2019,1992,25,Chelsea,Spain,58500000,45000000,FW,...,0,19,0,8,0,0,6,18,28,14.1
3,3,Álvaro Negredo,2016-2017,1985,30,Middlesbrough,Spain,8250000,6750000,FW,...,10,45,0,18,0,0,65,175,177,47.0
4,4,Abel Hernández,2016-2017,1990,25,Hull City,Uruguay,7200000,7200000,FW,...,3,19,0,8,0,0,3,22,50,14.6

In [260]:
#ovr['RANK']=ovr['OVR(%)'].rank(method='max')/16
#ovr.sort_values('OVR(%)',ascending=False).head()
ovr.columns

Index(['Unnamed: 0', 'Player', 'Season', 'Born ', 'Age', 'Squad', 'Nation',
       'Previous Market Value', 'Market Value', 'Position', 'App', 'Minutes',
       'Goals', 'Passes', 'Assists', 'Yellow', 'Red', 'SubOn', 'SubOff',
       'Shots', 'SOT', 'HitPost', 'HeadClear', 'HeadGoal', 'PKScored',
       'FKGoal', 'Offsides', 'ThrBall', 'Misses', 'Corners', 'Crosses',
       'Blocks', 'Interceptions', 'Fouls', 'Last man ', 'Tackles', 'ELG',
       'OwnGoal', 'Clears', 'ABW', 'ABL', 'OVR(%)'],
      dtype='object')

In [261]:
seasons = ovr.groupby(ovr['Season'])

In [262]:
season2015 = seasons.get_group('2018-2019')
s2015 = season2015.groupby(season2015['Position']).get_group("MF")

In [263]:
#s2015['Goals/avg'] = s2015['Goals']/(s2015['Goals'].sum()/len(s2015['Goals']))

In [264]:
#s2015.sort_values('Goals/avg',ascending=False).head()

In [265]:
#s2015['shots/avg']= s2015['Shots']/(s2015['Shots'].sum()/len(s2015['Shots']))
#s2015.sort_values('shots/avg',ascending=False).head()

In [266]:
#s2015['SOT/avg']= s2015['SOT']/(s2015['SOT'].sum()/len(s2015['SOT']))
#s2015.sort_values('SOT/avg',ascending=False).head()

In [267]:
#s2015['App/avg']= s2015['App']/(s2015['App'].sum()/len(s2015['App']))
#s2015.sort_values('App/avg',ascending=False).head()

In [268]:
s2015.head()

,Unnamed: 0,Player,Season,Born,Age,Squad,Nation,Previous Market Value,Market Value,Position,...,Interceptions,Fouls,Last man,Tackles,ELG,OwnGoal,Clears,ABW,ABL,OVR(%)
368,2,Aaron Lennon,2018-2019,1987,31,Burnley,England,5500000,5500000,MF,...,10,12,0,26,0,0,12,2,12,4.0
371,5,Aaron Mooy,2018-2019,1990,27,Huddersfield Town,Australia,11000000,15400000,MF,...,15,26,0,62,0,0,21,15,27,28.0
375,9,Aaron Ramsey,2018-2019,1990,27,Arsenal,Wales,49500000,44000000,MF,...,9,21,0,34,0,0,3,13,21,27.0
378,12,Abdoulaye Doucoure,2018-2019,1993,25,Watford,France,16500000,27500000,MF,...,34,36,0,71,1,1,54,41,37,37.5
384,18,Adam Lallana,2018-2019,1988,30,Liverpool,England,27500000,16500000,MF,...,5,4,0,16,0,0,0,9,14,3.6

In [269]:
s2015['OVR'] = s2015['OVR(%)']

<ipython-input-269-bd37422618ac>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s2015['OVR'] = s2015['OVR(%)']

In [270]:
'''for i in range(len(s2015)):
    if s2015['Goals/avg'].iloc[i] > 7:
        s2015['Goals/avg'].iloc[i] = 5
        goals_coeff = 3 
    elif s2015['Goals/avg'].iloc[i] < 7 and  s2015['Goals/avg'].iloc[i] > 4 :
        s2015['Goals/avg'].iloc[i] = 3
        goals_coeff =  2
    elif s2015['Goals/avg'].iloc[i] < 4 :
        s2015['Goals/avg'].iloc[i] = 1
        goals_coeff =  1

    if s2015['shots/avg'].iloc[i] > 7:
        s2015['shots/avg'].iloc[i] = 5
        shots_coeff = 3
    elif s2015['shots/avg'].iloc[i] < 7 and  s2015['Goals/avg'].iloc[i] > 4 :
        s2015['shots/avg'].iloc[i] =3
        shots_coeff =  2
    elif s2015['shots/avg'].iloc[i] < 4 :
        s2015['shots/avg'].iloc[i]  =1
        shots_coeff =  1

    if s2015['SOT/avg'].iloc[i] > 7:
         s2015['SOT/avg'].iloc[i] =5
         sot_coeff = 3
    elif s2015['SOT/avg'].iloc[i] < 7 and  s2015['Goals/avg'].iloc[i] > 4 :
         s2015['SOT/avg'].iloc[i] =3
         sot_coeff =  2
    elif s2015['SOT/avg'].iloc[i] < 4 :
         s2015['SOT/avg'].iloc[i]=1
         sot_coeff =  1
    
    n=0.88

    s2015['OVR'].iloc[i] = n*s2015['Goals/avg'].iloc[i]*goals_coeff + (n**2)*s2015['shots/avg'].iloc[i]*shots_coeff + (n**3)*s2015['SOT/avg'].iloc[i]*sot_coeff'''

"for i in range(len(s2015)):\n    if s2015['Goals/avg'].iloc[i] > 7:\n        s2015['Goals/avg'].iloc[i] = 5\n        goals_coeff = 3 \n    elif s2015['Goals/avg'].iloc[i] < 7 and  s2015['Goals/avg'].iloc[i] > 4 :\n        s2015['Goals/avg'].iloc[i] = 3\n        goals_coeff =  2\n    elif s2015['Goals/avg'].iloc[i] < 4 :\n        s2015['Goals/avg'].iloc[i] = 1\n        goals_coeff =  1\n\n    if s2015['shots/avg'].iloc[i] > 7:\n        s2015['shots/avg'].iloc[i] = 5\n        shots_coeff = 3\n    elif s2015['shots/avg'].iloc[i] < 7 and  s2015['Goals/avg'].iloc[i] > 4 :\n        s2015['shots/avg'].iloc[i] =3\n        shots_coeff =  2\n    elif s2015['shots/avg'].iloc[i] < 4 :\n        s2015['shots/avg'].iloc[i]  =1\n        shots_coeff =  1\n\n    if s2015['SOT/avg'].iloc[i] > 7:\n         s2015['SOT/avg'].iloc[i] =5\n         sot_coeff = 3\n    elif s2015['SOT/avg'].iloc[i] < 7 and  s2015['Goals/avg'].iloc[i] > 4 :\n         s2015['SOT/avg'].iloc[i] =3\n         sot_coeff =  2\n    elif s2015['SOT/avg'].iloc[i] < 4 :\n         s2015['SOT/avg'].iloc[i]=1\n         sot_coeff =  1\n    \n    n=0.88\n\n    s2015['OVR'].iloc[i] = n*s2015['Goals/avg'].iloc[i]*goals_coeff + (n**2)*s2015['shots/avg'].iloc[i]*shots_coeff + (n**3)*s2015['SOT/avg'].iloc[i]*sot_coeff"

In [271]:
#s2015['RANK']=s2015['OVR'].rank(method='max')

#s2015.sort_values('OVR',ascending=False).head()

In [272]:
#s2015.sort_values('RANK',ascending=True).head(5)

In [273]:
'''s2015["Goals_Rank"] = s2015['Goals'].rank(pct=True)
s2015["shots_Rank"] = s2015['Shots'].rank(pct=True)
s2015["sot_Rank"] = s2015['SOT'].rank(pct=True)'''

's2015["Goals_Rank"] = s2015[\'Goals\'].rank(pct=True)\ns2015["shots_Rank"] = s2015[\'Shots\'].rank(pct=True)\ns2015["sot_Rank"] = s2015[\'SOT\'].rank(pct=True)'

In [274]:
s2015.head()

,Unnamed: 0,Player,Season,Born,Age,Squad,Nation,Previous Market Value,Market Value,Position,...,Fouls,Last man,Tackles,ELG,OwnGoal,Clears,ABW,ABL,OVR(%),OVR
368,2,Aaron Lennon,2018-2019,1987,31,Burnley,England,5500000,5500000,MF,...,12,0,26,0,0,12,2,12,4.0,4.0
371,5,Aaron Mooy,2018-2019,1990,27,Huddersfield Town,Australia,11000000,15400000,MF,...,26,0,62,0,0,21,15,27,28.0,28.0
375,9,Aaron Ramsey,2018-2019,1990,27,Arsenal,Wales,49500000,44000000,MF,...,21,0,34,0,0,3,13,21,27.0,27.0
378,12,Abdoulaye Doucoure,2018-2019,1993,25,Watford,France,16500000,27500000,MF,...,36,0,71,1,1,54,41,37,37.5,37.5
384,18,Adam Lallana,2018-2019,1988,30,Liverpool,England,27500000,16500000,MF,...,4,0,16,0,0,0,9,14,3.6,3.6

In [275]:
s2015.columns

Index(['Unnamed: 0', 'Player', 'Season', 'Born ', 'Age', 'Squad', 'Nation',
       'Previous Market Value', 'Market Value', 'Position', 'App', 'Minutes',
       'Goals', 'Passes', 'Assists', 'Yellow', 'Red', 'SubOn', 'SubOff',
       'Shots', 'SOT', 'HitPost', 'HeadClear', 'HeadGoal', 'PKScored',
       'FKGoal', 'Offsides', 'ThrBall', 'Misses', 'Corners', 'Crosses',
       'Blocks', 'Interceptions', 'Fouls', 'Last man ', 'Tackles', 'ELG',
       'OwnGoal', 'Clears', 'ABW', 'ABL', 'OVR(%)', 'OVR'],
      dtype='object')

In [276]:
s2015["goals_Rank"] = s2015['Goals'].rank(pct=True)
s2015["passes_Rank"] = s2015['Passes'].rank(pct=True)
s2015["assits_Rank"] = s2015['Assists'].rank(pct=True)
s2015["ThrBall_Rank"] = s2015['ThrBall'].rank(pct=True)
s2015["Interception_Rank"] = s2015['Interceptions'].rank(pct=True)
s2015['Crosses_Rank'] = s2015['Crosses'].rank(pct=True)

<ipython-input-276-a2cbc47eca38>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s2015["goals_Rank"] = s2015['Goals'].rank(pct=True)
<ipython-input-276-a2cbc47eca38>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s2015["passes_Rank"] = s2015['Passes'].rank(pct=True)
<ipython-input-276-a2cbc47eca38>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s2015["assits_Rank"] = s2015['Assists'].rank(pct=True)
<ipython-input-276-a2cbc47eca38>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s2015["ThrBall_Rank"] = s2015['ThrBall'].rank(pct=True)
<ipython-input-276-a2cbc47eca38>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s2015["Interception_Rank"] = s2015['Interceptions'].rank(pct=True)
<ipython-input-276-a2cbc47eca38>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s2015['Crosses_Rank'] = s2015['Crosses'].rank(pct=True)

In [280]:
for i in range(len(s2015)):
    s2015['OVR'].iloc[i] = int((s2015['goals_Rank'].iloc[i]*0.1 +  s2015['assits_Rank'].iloc[i]*0.3 + s2015['passes_Rank'].iloc[i]*0.2 + s2015['Crosses_Rank'].iloc[i]*0.15+s2015['ThrBall_Rank'].iloc[i]*0.15+s2015['Interception_Rank'].iloc[i]*0.1)*100)
s2015.head()

/home/obafemi/.local/lib/python3.8/site-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

,Unnamed: 0,Player,Season,Born,Age,Squad,Nation,Previous Market Value,Market Value,Position,...,ABW,ABL,OVR(%),OVR,goals_Rank,passes_Rank,assits_Rank,ThrBall_Rank,Interception_Rank,Crosses_Rank
368,2,Aaron Lennon,2018-2019,1987,31,Burnley,England,5500000,5500000,MF,...,2,12,4.0,33.0,0.392086,0.118705,0.420863,0.255396,0.291367,0.543165
371,5,Aaron Mooy,2018-2019,1990,27,Huddersfield Town,Australia,11000000,15400000,MF,...,15,27,28.0,58.0,0.683453,0.748201,0.420863,0.406475,0.446043,0.920863
375,9,Aaron Ramsey,2018-2019,1990,27,Arsenal,Wales,49500000,44000000,MF,...,13,21,27.0,64.0,0.769784,0.496403,0.917266,0.708633,0.258993,0.406475
378,12,Abdoulaye Doucoure,2018-2019,1993,25,Watford,France,16500000,27500000,MF,...,41,37,37.5,78.0,0.827338,0.942446,0.917266,0.708633,0.809353,0.345324
384,18,Adam Lallana,2018-2019,1988,30,Liverpool,England,27500000,16500000,MF,...,9,14,3.6,17.0,0.143885,0.129496,0.158273,0.255396,0.115108,0.258993

In [282]:
s2015.sort_values('OVR',ascending=False).head(20)

,Unnamed: 0,Player,Season,Born,Age,Squad,Nation,Previous Market Value,Market Value,Position,...,ABW,ABL,OVR(%),OVR,goals_Rank,passes_Rank,assits_Rank,ThrBall_Rank,Interception_Rank,Crosses_Rank
484,118,David Silva,2018-2019,1986,32,Manchester City,Spain,11000000,16500000,MF,...,20,23,46.1,90.0,0.888489,0.964029,0.971223,0.967626,0.629496,0.802158
458,92,Christian Eriksen,2018-2019,1992,26,Tottenham,Denmark,4400000,4400000,MF,...,13,34,71.3,90.0,0.971223,0.928058,0.992806,0.992806,0.446043,0.874101
816,450,Paul Pogba,2018-2019,1993,25,Manchester United,France,8000000,8000000,MF,...,59,61,85.6,87.0,0.996403,0.985612,0.985612,0.942446,0.525180,0.607914
434,68,Bernardo Silva,2018-2019,1994,23,Manchester City,Portugal,45000000,90000000,MF,...,11,27,47.8,87.0,0.946043,0.870504,0.949640,0.892086,0.679856,0.776978
591,225,James Maddison,2018-2019,1996,21,Leicester City,England,6300000,6300000,MF,...,11,34,66.0,87.0,0.946043,0.798561,0.949640,0.985612,0.366906,0.985612
560,194,Gylfi Sigurdsson,2018-2019,1989,29,Everton,Iceland,1350000,1800000,MF,...,19,42,70.9,86.0,0.996403,0.618705,0.917266,0.978417,0.715827,0.974820
856,490,Ryan Fraser,2018-2019,1994,24,AFC Bournemouth,Scotland,5400000,27000000,MF,...,11,28,45.8,86.0,0.946043,0.726619,1.000000,0.773381,0.629496,1.000000
580,214,Ilkay Gündogan,2018-2019,1990,27,Manchester City,Germany,7500000,6500000,MF,...,26,24,36.2,84.0,0.888489,0.956835,0.726619,0.956835,0.715827,0.848921
627,261,João Moutinho,2018-2019,1986,31,Wolves,Portugal,11000000,8800000,MF,...,21,40,15.7,84.0,0.392086,0.920863,0.971223,0.629496,0.856115,0.974820
746,380,Matt Ritchie,2018-2019,1989,28,Newcastle United,Scotland,6300000,31500000,MF,...,35,65,29.4,82.0,0.564748,0.676259,0.971223,0.708633,0.906475,0.992806
423,57,Ashley Westwood,2018-2019,1990,28,Burnley,England,4400000,7700000,MF,...,20,18,19.3,82.0,0.564748,0.805755,0.949640,0.708633,0.895683,0.834532
835,469,Ricardo Pereira,2018-2019,1993,24,Leicester City,Portugal,18000000,22500000,MF,...,66,75,20.3,80.0,0.564748,0.827338,0.917266,0.532374,0.946043,0.856115
828,462,Rúben Neves,2018-2019,1997,21,Wolves,Portugal,22500000,40500000,MF,...,31,35,48.0,80.0,0.769784,0.935252,0.726619,0.913669,0.982014,0.561151
903,537,Víctor Camarasa,2018-2019,1994,24,Cardiff City,Spain,5400000,9000000,MF,...,20,31,34.2,79.0,0.827338,0.561151,0.812950,0.931655,0.791367,0.892086
603,237,James Milner,2018-2019,1986,32,Liverpool,England,13200000,16500000,MF,...,20,28,20.8,79.0,0.827338,0.791367,0.812950,0.773381,0.525180,0.913669
825,459,Pierre-Emile Højbjerg,2018-2019,1995,23,Southampton,Denmark,8800000,8800000,MF,...,48,30,38.4,78.0,0.769784,0.906475,0.726619,0.820144,0.946043,0.625899
378,12,Abdoulaye Doucoure,2018-2019,1993,25,Watford,France,16500000,27500000,MF,...,41,37,37.5,78.0,0.827338,0.942446,0.917266,0.708633,0.809353,0.345324
554,188,Granit Xhaka,2018-2019,1992,25,Arsenal,Switzerland,2000000,2000000,MF,...,52,41,22.9,78.0,0.769784,0.992806,0.600719,0.708633,0.823741,0.906475
782,416,N'Golo Kanté,2018-2019,1991,27,Chelsea,France,58500000,54000000,MF,...,27,41,20.8,77.0,0.769784,0.971223,0.812950,0.629496,0.884892,0.482014
729,363,Mark Noble,2018-2019,1987,31,West Ham United,England,4500000,4500000,MF,...,8,8,20.1,77.0,0.827338,0.820144,0.870504,0.892086,0.600719,0.517986