In [21]:
import pandas as pd

In [284]:
ovr = pd.read_csv('OVR_data.csv')

ValueError: Boolean array expected for the condition, not int64

In [148]:
ovr.head(5)

,Unnamed: 0,Player,Season,Born,Age,Squad,Nation,Previous Market Value,Market Value,Position,...,Interceptions,Fouls,Last man,Tackles,ELG,OwnGoal,Clears,ABW,ABL,OVR(%)
0,0,Éder,2015-2016,1987,27,Swansea City,Portugal,5500000,4500000,FW,...,0,11,0,4,0,0,7,9,20,3.0
1,1,Álvaro Morata,2017-2018,1992,25,Chelsea,Spain,44000000,58500000,FW,...,6,41,0,13,0,0,20,54,59,36.9
2,2,Álvaro Morata,2018-2019,1992,25,Chelsea,Spain,58500000,45000000,FW,...,0,19,0,8,0,0,6,18,28,14.1
3,3,Álvaro Negredo,2016-2017,1985,30,Middlesbrough,Spain,8250000,6750000,FW,...,10,45,0,18,0,0,65,175,177,47.0
4,4,Abel Hernández,2016-2017,1990,25,Hull City,Uruguay,7200000,7200000,FW,...,3,19,0,8,0,0,3,22,50,14.6

In [149]:
#ovr['RANK']=ovr['OVR(%)'].rank(method='max')/16
#ovr.sort_values('OVR(%)',ascending=False).head()
ovr.columns

Index(['Unnamed: 0', 'Player', 'Season', 'Born ', 'Age', 'Squad', 'Nation',
       'Previous Market Value', 'Market Value', 'Position', 'App', 'Minutes',
       'Goals', 'Passes', 'Assists', 'Yellow', 'Red', 'SubOn', 'SubOff',
       'Shots', 'SOT', 'HitPost', 'HeadClear', 'HeadGoal', 'PKScored',
       'FKGoal', 'Offsides', 'ThrBall', 'Misses', 'Corners', 'Crosses',
       'Blocks', 'Interceptions', 'Fouls', 'Last man ', 'Tackles', 'ELG',
       'OwnGoal', 'Clears', 'ABW', 'ABL', 'OVR(%)'],
      dtype='object')

In [150]:
seasons = ovr.groupby(ovr['Season'])

In [151]:
season2015 = seasons.get_group('2018-2019')
s2015 = season2015.groupby(season2015['Position']).get_group("DF")

In [152]:
#s2015['Goals/avg'] = s2015['Goals']/(s2015['Goals'].sum()/len(s2015['Goals']))

In [153]:
#s2015.sort_values('Goals/avg',ascending=False).head()

In [154]:
#s2015['shots/avg']= s2015['Shots']/(s2015['Shots'].sum()/len(s2015['Shots']))
#s2015.sort_values('shots/avg',ascending=False).head()

In [155]:
#s2015['SOT/avg']= s2015['SOT']/(s2015['SOT'].sum()/len(s2015['SOT']))
#s2015.sort_values('SOT/avg',ascending=False).head()

In [156]:
#s2015['App/avg']= s2015['App']/(s2015['App'].sum()/len(s2015['App']))
#s2015.sort_values('App/avg',ascending=False).head()

In [157]:
s2015.head()

,Unnamed: 0,Player,Season,Born,Age,Squad,Nation,Previous Market Value,Market Value,Position,...,Interceptions,Fouls,Last man,Tackles,ELG,OwnGoal,Clears,ABW,ABL,OVR(%)
2,2,Álvaro Morata,2018-2019,1992,25,Chelsea,Spain,58500000,45000000,FW,...,0,19,0,8,0,0,6,18,28,14.1
5,5,Aboubakar Kamara,2018-2019,1995,23,Fulham,France,4400000,2480000,FW,...,1,24,0,8,0,0,5,12,15,12.1
6,6,Adama Diakhaby,2018-2019,1996,22,Huddersfield Town,France,7700000,7200000,FW,...,1,7,0,6,0,0,1,6,15,6.4
9,9,Adama Traoré,2018-2019,1996,22,Wolves,Spain,16500000,13500000,FW,...,6,15,0,16,0,0,6,22,36,13.8
10,10,Ademola Lookman,2018-2019,1997,20,Everton,England,10800000,18000000,FW,...,7,8,0,15,0,0,2,6,5,12.3

In [167]:
s2015['OVR'] = s2015['OVR(%)']

<ipython-input-167-bd37422618ac>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s2015['OVR'] = s2015['OVR(%)']

In [159]:
'''for i in range(len(s2015)):
    if s2015['Goals/avg'].iloc[i] > 7:
        s2015['Goals/avg'].iloc[i] = 5
        goals_coeff = 3 
    elif s2015['Goals/avg'].iloc[i] < 7 and  s2015['Goals/avg'].iloc[i] > 4 :
        s2015['Goals/avg'].iloc[i] = 3
        goals_coeff =  2
    elif s2015['Goals/avg'].iloc[i] < 4 :
        s2015['Goals/avg'].iloc[i] = 1
        goals_coeff =  1

    if s2015['shots/avg'].iloc[i] > 7:
        s2015['shots/avg'].iloc[i] = 5
        shots_coeff = 3
    elif s2015['shots/avg'].iloc[i] < 7 and  s2015['Goals/avg'].iloc[i] > 4 :
        s2015['shots/avg'].iloc[i] =3
        shots_coeff =  2
    elif s2015['shots/avg'].iloc[i] < 4 :
        s2015['shots/avg'].iloc[i]  =1
        shots_coeff =  1

    if s2015['SOT/avg'].iloc[i] > 7:
         s2015['SOT/avg'].iloc[i] =5
         sot_coeff = 3
    elif s2015['SOT/avg'].iloc[i] < 7 and  s2015['Goals/avg'].iloc[i] > 4 :
         s2015['SOT/avg'].iloc[i] =3
         sot_coeff =  2
    elif s2015['SOT/avg'].iloc[i] < 4 :
         s2015['SOT/avg'].iloc[i]=1
         sot_coeff =  1
    
    n=0.88

    s2015['OVR'].iloc[i] = n*s2015['Goals/avg'].iloc[i]*goals_coeff + (n**2)*s2015['shots/avg'].iloc[i]*shots_coeff + (n**3)*s2015['SOT/avg'].iloc[i]*sot_coeff'''

"for i in range(len(s2015)):\n    if s2015['Goals/avg'].iloc[i] > 7:\n        s2015['Goals/avg'].iloc[i] = 5\n        goals_coeff = 3 \n    elif s2015['Goals/avg'].iloc[i] < 7 and  s2015['Goals/avg'].iloc[i] > 4 :\n        s2015['Goals/avg'].iloc[i] = 3\n        goals_coeff =  2\n    elif s2015['Goals/avg'].iloc[i] < 4 :\n        s2015['Goals/avg'].iloc[i] = 1\n        goals_coeff =  1\n\n    if s2015['shots/avg'].iloc[i] > 7:\n        s2015['shots/avg'].iloc[i] = 5\n        shots_coeff = 3\n    elif s2015['shots/avg'].iloc[i] < 7 and  s2015['Goals/avg'].iloc[i] > 4 :\n        s2015['shots/avg'].iloc[i] =3\n        shots_coeff =  2\n    elif s2015['shots/avg'].iloc[i] < 4 :\n        s2015['shots/avg'].iloc[i]  =1\n        shots_coeff =  1\n\n    if s2015['SOT/avg'].iloc[i] > 7:\n         s2015['SOT/avg'].iloc[i] =5\n         sot_coeff = 3\n    elif s2015['SOT/avg'].iloc[i] < 7 and  s2015['Goals/avg'].iloc[i] > 4 :\n         s2015['SOT/avg'].iloc[i] =3\n         sot_coeff =  2\n    elif s2015['SOT/avg'].iloc[i] < 4 :\n         s2015['SOT/avg'].iloc[i]=1\n         sot_coeff =  1\n    \n    n=0.88\n\n    s2015['OVR'].iloc[i] = n*s2015['Goals/avg'].iloc[i]*goals_coeff + (n**2)*s2015['shots/avg'].iloc[i]*shots_coeff + (n**3)*s2015['SOT/avg'].iloc[i]*sot_coeff"

In [160]:
#s2015['RANK']=s2015['OVR'].rank(method='max')

#s2015.sort_values('OVR',ascending=False).head()

In [161]:
#s2015.sort_values('RANK',ascending=True).head(5)

In [162]:
'''s2015["Goals_Rank"] = s2015['Goals'].rank(pct=True)
s2015["shots_Rank"] = s2015['Shots'].rank(pct=True)
s2015["sot_Rank"] = s2015['SOT'].rank(pct=True)'''

's2015["Goals_Rank"] = s2015[\'Goals\'].rank(pct=True)\ns2015["shots_Rank"] = s2015[\'Shots\'].rank(pct=True)\ns2015["sot_Rank"] = s2015[\'SOT\'].rank(pct=True)'

In [168]:
s2015.head()

,Unnamed: 0,Player,Season,Born,Age,Squad,Nation,Previous Market Value,Market Value,Position,...,ABW,ABL,OVR(%),goals_Rank,passes_Rank,assits_Rank,SOT_Rank,HeadGoal_Rank,shots_Rank,OVR
2,2,Álvaro Morata,2018-2019,1992,25,Chelsea,Spain,58500000,45000000,FW,...,18,28,14.1,0.556180,0.280899,0.168539,0.539326,0.297753,0.528090,14.1
5,5,Aboubakar Kamara,2018-2019,1995,23,Fulham,France,4400000,2480000,FW,...,12,15,12.1,0.460674,0.269663,0.168539,0.455056,0.297753,0.320225,12.1
6,6,Adama Diakhaby,2018-2019,1996,22,Huddersfield Town,France,7700000,7200000,FW,...,6,15,6.4,0.095506,0.134831,0.168539,0.078652,0.297753,0.061798,6.4
9,9,Adama Traoré,2018-2019,1996,22,Wolves,Spain,16500000,13500000,FW,...,22,36,13.8,0.095506,0.382022,0.168539,0.286517,0.297753,0.258427,13.8
10,10,Ademola Lookman,2018-2019,1997,20,Everton,England,10800000,18000000,FW,...,6,5,12.3,0.095506,0.325843,0.544944,0.078652,0.297753,0.112360,12.3

In [169]:
s2015.columns

Index(['Unnamed: 0', 'Player', 'Season', 'Born ', 'Age', 'Squad', 'Nation',
       'Previous Market Value', 'Market Value', 'Position', 'App', 'Minutes',
       'Goals', 'Passes', 'Assists', 'Yellow', 'Red', 'SubOn', 'SubOff',
       'Shots', 'SOT', 'HitPost', 'HeadClear', 'HeadGoal', 'PKScored',
       'FKGoal', 'Offsides', 'ThrBall', 'Misses', 'Corners', 'Crosses',
       'Blocks', 'Interceptions', 'Fouls', 'Last man ', 'Tackles', 'ELG',
       'OwnGoal', 'Clears', 'ABW', 'ABL', 'OVR(%)', 'goals_Rank',
       'passes_Rank', 'assits_Rank', 'SOT_Rank', 'HeadGoal_Rank', 'shots_Rank',
       'OVR'],
      dtype='object')

In [170]:
s2015["goals_Rank"] = s2015['Goals'].rank(pct=True)
s2015["passes_Rank"] = s2015['Passes'].rank(pct=True)
s2015["assits_Rank"] = s2015['Assists'].rank(pct=True)
s2015["SOT_Rank"] = s2015['SOT'].rank(pct=True)
s2015["HeadGoal_Rank"] = s2015['HeadGoal'].rank(pct=True)
s2015['shots_Rank'] = s2015['Shots'].rank(pct=True)

<ipython-input-170-3be602ce3739>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s2015["goals_Rank"] = s2015['Goals'].rank(pct=True)
<ipython-input-170-3be602ce3739>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s2015["passes_Rank"] = s2015['Passes'].rank(pct=True)
<ipython-input-170-3be602ce3739>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s2015["assits_Rank"] = s2015['Assists'].rank(pct=True)
<ipython-input-170-3be602ce3739>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s2015["SOT_Rank"] = s2015['SOT'].rank(pct=True)
<ipython-input-170-3be602ce3739>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s2015["HeadGoal_Rank"] = s2015['HeadGoal'].rank(pct=True)
<ipython-input-170-3be602ce3739>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s2015['shots_Rank'] = s2015['Shots'].rank(pct=True)

In [171]:
for i in range(len(s2015)):
    s2015['OVR'].iloc[i] = int((s2015['goals_Rank'].iloc[i]*0.35 +  s2015['assits_Rank'].iloc[i]*0.2 + s2015['passes_Rank'].iloc[i]*0.1 + s2015['SOT_Rank'].iloc[i]*0.25+ s2015['shots_Rank'].iloc[i]*0.1)*100)
s2015.head()

/home/obafemi/.local/lib/python3.8/site-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

,Unnamed: 0,Player,Season,Born,Age,Squad,Nation,Previous Market Value,Market Value,Position,...,ABW,ABL,OVR(%),goals_Rank,passes_Rank,assits_Rank,SOT_Rank,HeadGoal_Rank,shots_Rank,OVR
2,2,Álvaro Morata,2018-2019,1992,25,Chelsea,Spain,58500000,45000000,FW,...,18,28,14.1,0.556180,0.280899,0.168539,0.539326,0.297753,0.528090,44.0
5,5,Aboubakar Kamara,2018-2019,1995,23,Fulham,France,4400000,2480000,FW,...,12,15,12.1,0.460674,0.269663,0.168539,0.455056,0.297753,0.320225,36.0
6,6,Adama Diakhaby,2018-2019,1996,22,Huddersfield Town,France,7700000,7200000,FW,...,6,15,6.4,0.095506,0.134831,0.168539,0.078652,0.297753,0.061798,10.0
9,9,Adama Traoré,2018-2019,1996,22,Wolves,Spain,16500000,13500000,FW,...,22,36,13.8,0.095506,0.382022,0.168539,0.286517,0.297753,0.258427,20.0
10,10,Ademola Lookman,2018-2019,1997,20,Everton,England,10800000,18000000,FW,...,6,5,12.3,0.095506,0.325843,0.544944,0.078652,0.297753,0.112360,20.0

In [172]:
s2015.sort_values('OVR',ascending=False).head(20)

,Unnamed: 0,Player,Season,Born,Age,Squad,Nation,Previous Market Value,Market Value,Position,...,ABW,ABL,OVR(%),goals_Rank,passes_Rank,assits_Rank,SOT_Rank,HeadGoal_Rank,shots_Rank,OVR
249,249,Mohamed Salah,2018-2019,1992,26,Liverpool,Egypt,135000000,165000000,FW,...,11,60,69.1,0.988764,0.932584,0.943820,1.000000,0.297753,1.000000,97.0
113,113,Eden Hazard,2018-2019,1991,27,Chelsea,Belgium,99000000,135000000,FW,...,20,33,100.0,0.921348,1.000000,1.000000,0.960674,0.297753,0.932584,95.0
315,315,Sergio Agüero,2018-2019,1988,30,Manchester City,Argentina,72000000,58500000,FW,...,17,22,51.7,0.966292,0.803371,0.943820,0.960674,0.803371,0.977528,94.0
279,279,Raheem Sterling,2018-2019,1994,23,Manchester City,England,81000000,126000000,FW,...,15,28,70.8,0.938202,0.966292,0.983146,0.898876,0.803371,0.853933,93.0
274,274,Raúl Jiménez,2018-2019,1991,27,Wolves,Mexico,16500000,31500000,FW,...,78,107,64.3,0.882022,0.910112,0.915730,0.887640,0.921348,0.966292,90.0
273,273,Pierre-Emerick Aubameyang,2018-2019,1989,29,Arsenal,Gabon,82500000,77000000,FW,...,32,83,45.0,0.988764,0.719101,0.814607,0.921348,0.297753,0.943820,90.0
21,21,Alexandre Lacazette,2018-2019,1991,27,Arsenal,France,54000000,63000000,FW,...,47,93,46.8,0.882022,0.803371,0.943820,0.825843,0.297753,0.876404,87.0
151,151,Harry Kane,2018-2019,1993,25,Tottenham,England,108000000,135000000,FW,...,49,68,38.7,0.938202,0.617978,0.747191,0.977528,0.803371,0.955056,87.0
290,290,Roberto Firmino,2018-2019,1991,26,Liverpool,Brazil,72000000,72000000,FW,...,30,76,70.8,0.825843,0.977528,0.870787,0.876404,0.921348,0.842697,86.0
165,165,Jamie Vardy,2018-2019,1987,31,Leicester City,England,18000000,18000000,FW,...,67,109,29.5,0.955056,0.561798,0.747191,0.921348,0.921348,0.865169,85.0
60,60,Callum Wilson,2018-2019,1992,26,AFC Bournemouth,England,9000000,27000000,FW,...,46,90,29.0,0.910112,0.573034,0.966292,0.825843,0.921348,0.786517,85.0
299,299,Sadio Mané,2018-2019,1992,26,Liverpool,Senegal,63000000,108000000,FW,...,37,76,67.9,0.988764,0.943820,0.404494,0.943820,0.988764,0.910112,84.0
14,14,Aleksandar Mitrovic,2018-2019,1994,24,Fulham,Serbia,13500000,22500000,FW,...,240,245,64.8,0.780899,0.898876,0.657303,0.988764,0.988764,0.988764,84.0
327,327,Son Heung-Min,2018-2019,1992,26,Tottenham,South Korea,45000000,72000000,FW,...,4,31,44.9,0.825843,0.786517,0.870787,0.786517,0.297753,0.831461,82.0
305,305,Salomón Rondón,2018-2019,1989,28,Newcastle United,Venezuela,11700000,13500000,FW,...,146,234,45.8,0.780899,0.775281,0.915730,0.786517,0.803371,0.921348,82.0
227,227,Marcus Rashford,2018-2019,1997,20,Manchester United,England,58500000,72000000,FW,...,29,44,41.8,0.724719,0.696629,0.870787,0.921348,0.297753,0.898876,81.0
209,209,Leroy Sané,2018-2019,1996,22,Manchester City,Germany,81000000,90000000,FW,...,10,23,47.5,0.724719,0.865169,0.983146,0.696629,0.297753,0.674157,77.0
360,360,Wilfried Zaha,2018-2019,1992,25,Crystal Palace,Cote D'Ivoire,27000000,40500000,FW,...,9,35,57.0,0.724719,0.887640,0.814607,0.752809,0.297753,0.820225,77.0
344,344,Troy Deeney,2018-2019,1988,30,Watford,England,9000000,9000000,FW,...,209,228,47.2,0.668539,0.853933,0.814607,0.825843,0.921348,0.764045,76.0
231,231,Marko Arnautovic,2018-2019,1989,29,West Ham United,Austria,22500000,31500000,FW,...,24,26,37.9,0.724719,0.685393,0.747191,0.859551,0.657303,0.747191,76.0