In [186]:
import pandas as pd

In [187]:
ovr = pd.read_csv('OVR_data.csv')

In [188]:
ovr.head(5)

,Unnamed: 0,Player,Season,Born,Age,Squad,Nation,Previous Market Value,Market Value,Position,...,Interceptions,Fouls,Last man,Tackles,ELG,OwnGoal,Clears,ABW,ABL,OVR(%)
0,0,Éder,2015-2016,1987,27,Swansea City,Portugal,5500000,4500000,FW,...,0,11,0,4,0,0,7,9,20,3.0
1,1,Álvaro Morata,2017-2018,1992,25,Chelsea,Spain,44000000,58500000,FW,...,6,41,0,13,0,0,20,54,59,36.9
2,2,Álvaro Morata,2018-2019,1992,25,Chelsea,Spain,58500000,45000000,FW,...,0,19,0,8,0,0,6,18,28,14.1
3,3,Álvaro Negredo,2016-2017,1985,30,Middlesbrough,Spain,8250000,6750000,FW,...,10,45,0,18,0,0,65,175,177,47.0
4,4,Abel Hernández,2016-2017,1990,25,Hull City,Uruguay,7200000,7200000,FW,...,3,19,0,8,0,0,3,22,50,14.6

In [189]:
#ovr['RANK']=ovr['OVR(%)'].rank(method='max')/16
#ovr.sort_values('OVR(%)',ascending=False).head()
ovr.columns

Index(['Unnamed: 0', 'Player', 'Season', 'Born ', 'Age', 'Squad', 'Nation',
       'Previous Market Value', 'Market Value', 'Position', 'App', 'Minutes',
       'Goals', 'Passes', 'Assists', 'Yellow', 'Red', 'SubOn', 'SubOff',
       'Shots', 'SOT', 'HitPost', 'HeadClear', 'HeadGoal', 'PKScored',
       'FKGoal', 'Offsides', 'ThrBall', 'Misses', 'Corners', 'Crosses',
       'Blocks', 'Interceptions', 'Fouls', 'Last man ', 'Tackles', 'ELG',
       'OwnGoal', 'Clears', 'ABW', 'ABL', 'OVR(%)'],
      dtype='object')

In [190]:
seasons = ovr.groupby(ovr['Season'])

In [191]:
season2015 = seasons.get_group('2018-2019')
s2015 = season2015.groupby(season2015['Position']).get_group("DF")

In [192]:
#s2015['Goals/avg'] = s2015['Goals']/(s2015['Goals'].sum()/len(s2015['Goals']))

In [193]:
#s2015.sort_values('Goals/avg',ascending=False).head()

In [194]:
#s2015['shots/avg']= s2015['Shots']/(s2015['Shots'].sum()/len(s2015['Shots']))
#s2015.sort_values('shots/avg',ascending=False).head()

In [195]:
#s2015['SOT/avg']= s2015['SOT']/(s2015['SOT'].sum()/len(s2015['SOT']))
#s2015.sort_values('SOT/avg',ascending=False).head()

In [196]:
#s2015['App/avg']= s2015['App']/(s2015['App'].sum()/len(s2015['App']))
#s2015.sort_values('App/avg',ascending=False).head()

In [197]:
s2015.head()

,Unnamed: 0,Player,Season,Born,Age,Squad,Nation,Previous Market Value,Market Value,Position,...,Interceptions,Fouls,Last man,Tackles,ELG,OwnGoal,Clears,ABW,ABL,OVR(%)
941,0,Aaron Cresswell,2018-2019,1989,28,West Ham United,England,13200000,9900000,DF,...,23,2,1,29,0,0,42,25,18,24.6
945,4,Aaron Wan-Bissaka,2018-2019,1997,21,Crystal Palace,England,900000,31500000,DF,...,84,23,0,129,0,0,129,43,30,36.2
947,6,Adam Masina,2018-2019,1994,24,Watford,Italy,6300000,6300000,DF,...,17,17,0,30,0,0,36,23,15,11.8
948,7,Adam Smith,2018-2019,1991,27,AFC Bournemouth,England,4500000,6300000,DF,...,31,18,0,46,0,0,57,28,31,26.4
954,13,Adrian Mariappa,2018-2019,1986,31,Watford,Jamaica,1350000,2700000,DF,...,25,19,2,35,1,0,119,59,58,26.7

In [198]:
s2015['OVR'] = s2015['OVR(%)']

<ipython-input-198-bd37422618ac>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s2015['OVR'] = s2015['OVR(%)']

In [199]:
'''for i in range(len(s2015)):
    if s2015['Goals/avg'].iloc[i] > 7:
        s2015['Goals/avg'].iloc[i] = 5
        goals_coeff = 3 
    elif s2015['Goals/avg'].iloc[i] < 7 and  s2015['Goals/avg'].iloc[i] > 4 :
        s2015['Goals/avg'].iloc[i] = 3
        goals_coeff =  2
    elif s2015['Goals/avg'].iloc[i] < 4 :
        s2015['Goals/avg'].iloc[i] = 1
        goals_coeff =  1

    if s2015['shots/avg'].iloc[i] > 7:
        s2015['shots/avg'].iloc[i] = 5
        shots_coeff = 3
    elif s2015['shots/avg'].iloc[i] < 7 and  s2015['Goals/avg'].iloc[i] > 4 :
        s2015['shots/avg'].iloc[i] =3
        shots_coeff =  2
    elif s2015['shots/avg'].iloc[i] < 4 :
        s2015['shots/avg'].iloc[i]  =1
        shots_coeff =  1

    if s2015['SOT/avg'].iloc[i] > 7:
         s2015['SOT/avg'].iloc[i] =5
         sot_coeff = 3
    elif s2015['SOT/avg'].iloc[i] < 7 and  s2015['Goals/avg'].iloc[i] > 4 :
         s2015['SOT/avg'].iloc[i] =3
         sot_coeff =  2
    elif s2015['SOT/avg'].iloc[i] < 4 :
         s2015['SOT/avg'].iloc[i]=1
         sot_coeff =  1
    
    n=0.88

    s2015['OVR'].iloc[i] = n*s2015['Goals/avg'].iloc[i]*goals_coeff + (n**2)*s2015['shots/avg'].iloc[i]*shots_coeff + (n**3)*s2015['SOT/avg'].iloc[i]*sot_coeff'''

"for i in range(len(s2015)):\n    if s2015['Goals/avg'].iloc[i] > 7:\n        s2015['Goals/avg'].iloc[i] = 5\n        goals_coeff = 3 \n    elif s2015['Goals/avg'].iloc[i] < 7 and  s2015['Goals/avg'].iloc[i] > 4 :\n        s2015['Goals/avg'].iloc[i] = 3\n        goals_coeff =  2\n    elif s2015['Goals/avg'].iloc[i] < 4 :\n        s2015['Goals/avg'].iloc[i] = 1\n        goals_coeff =  1\n\n    if s2015['shots/avg'].iloc[i] > 7:\n        s2015['shots/avg'].iloc[i] = 5\n        shots_coeff = 3\n    elif s2015['shots/avg'].iloc[i] < 7 and  s2015['Goals/avg'].iloc[i] > 4 :\n        s2015['shots/avg'].iloc[i] =3\n        shots_coeff =  2\n    elif s2015['shots/avg'].iloc[i] < 4 :\n        s2015['shots/avg'].iloc[i]  =1\n        shots_coeff =  1\n\n    if s2015['SOT/avg'].iloc[i] > 7:\n         s2015['SOT/avg'].iloc[i] =5\n         sot_coeff = 3\n    elif s2015['SOT/avg'].iloc[i] < 7 and  s2015['Goals/avg'].iloc[i] > 4 :\n         s2015['SOT/avg'].iloc[i] =3\n         sot_coeff =  2\n    elif s2015['SOT/avg'].iloc[i] < 4 :\n         s2015['SOT/avg'].iloc[i]=1\n         sot_coeff =  1\n    \n    n=0.88\n\n    s2015['OVR'].iloc[i] = n*s2015['Goals/avg'].iloc[i]*goals_coeff + (n**2)*s2015['shots/avg'].iloc[i]*shots_coeff + (n**3)*s2015['SOT/avg'].iloc[i]*sot_coeff"

In [200]:
#s2015['RANK']=s2015['OVR'].rank(method='max')

#s2015.sort_values('OVR',ascending=False).head()

In [201]:
#s2015.sort_values('RANK',ascending=True).head(5)

In [202]:
'''s2015["Goals_Rank"] = s2015['Goals'].rank(pct=True)
s2015["shots_Rank"] = s2015['Shots'].rank(pct=True)
s2015["sot_Rank"] = s2015['SOT'].rank(pct=True)'''

's2015["Goals_Rank"] = s2015[\'Goals\'].rank(pct=True)\ns2015["shots_Rank"] = s2015[\'Shots\'].rank(pct=True)\ns2015["sot_Rank"] = s2015[\'SOT\'].rank(pct=True)'

In [203]:
s2015.head()

,Unnamed: 0,Player,Season,Born,Age,Squad,Nation,Previous Market Value,Market Value,Position,...,Fouls,Last man,Tackles,ELG,OwnGoal,Clears,ABW,ABL,OVR(%),OVR
941,0,Aaron Cresswell,2018-2019,1989,28,West Ham United,England,13200000,9900000,DF,...,2,1,29,0,0,42,25,18,24.6,24.6
945,4,Aaron Wan-Bissaka,2018-2019,1997,21,Crystal Palace,England,900000,31500000,DF,...,23,0,129,0,0,129,43,30,36.2,36.2
947,6,Adam Masina,2018-2019,1994,24,Watford,Italy,6300000,6300000,DF,...,17,0,30,0,0,36,23,15,11.8,11.8
948,7,Adam Smith,2018-2019,1991,27,AFC Bournemouth,England,4500000,6300000,DF,...,18,0,46,0,0,57,28,31,26.4,26.4
954,13,Adrian Mariappa,2018-2019,1986,31,Watford,Jamaica,1350000,2700000,DF,...,19,2,35,1,0,119,59,58,26.7,26.7

In [204]:
s2015.columns

Index(['Unnamed: 0', 'Player', 'Season', 'Born ', 'Age', 'Squad', 'Nation',
       'Previous Market Value', 'Market Value', 'Position', 'App', 'Minutes',
       'Goals', 'Passes', 'Assists', 'Yellow', 'Red', 'SubOn', 'SubOff',
       'Shots', 'SOT', 'HitPost', 'HeadClear', 'HeadGoal', 'PKScored',
       'FKGoal', 'Offsides', 'ThrBall', 'Misses', 'Corners', 'Crosses',
       'Blocks', 'Interceptions', 'Fouls', 'Last man ', 'Tackles', 'ELG',
       'OwnGoal', 'Clears', 'ABW', 'ABL', 'OVR(%)', 'OVR'],
      dtype='object')

In [207]:
s2015["goals_Rank"] = s2015['Goals'].rank(pct=True)
s2015["passes_Rank"] = s2015['Passes'].rank(pct=True)
s2015["HeadClear_Rank"] = s2015['HeadClear'].rank(pct=True)
s2015["Blocks_Rank"] = s2015['Blocks'].rank(pct=True)
s2015["HeadGoal_Rank"] = s2015['HeadGoal'].rank(pct=True)
s2015['Interceptions_Rank'] = s2015['Interceptions'].rank(pct=True)
s2015["tackles_Rank"] = s2015['Tackles'].rank(pct=True)

<ipython-input-207-f82288172df2>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s2015["goals_Rank"] = s2015['Goals'].rank(pct=True)
<ipython-input-207-f82288172df2>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s2015["passes_Rank"] = s2015['Passes'].rank(pct=True)
<ipython-input-207-f82288172df2>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s2015["HeadClear_Rank"] = s2015['HeadClear'].rank(pct=True)
<ipython-input-207-f82288172df2>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s2015["Blocks_Rank"] = s2015['Blocks'].rank(pct=True)
<ipython-input-207-f82288172df2>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s2015["HeadGoal_Rank"] = s2015['HeadGoal'].rank(pct=True)
<ipython-input-207-f82288172df2>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s2015['Interceptions_Rank'] = s2015['Interceptions'].rank(pct=True)
<ipython-input-207-f82288172df2>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s2015["tackles_Rank"] = s2015['Tackles'].rank(pct=True)

In [208]:
for i in range(len(s2015)):
    s2015['OVR'].iloc[i] = int((s2015['goals_Rank'].iloc[i]*0.1 +  s2015['tackles_Rank'].iloc[i]*0.2 + s2015['passes_Rank'].iloc[i]*0.1 + s2015['Blocks_Rank'].iloc[i]*0.20+ s2015['HeadGoal_Rank'].iloc[i]*0.1 + s2015['Interceptions_Rank'].iloc[i]*0.20+ s2015['HeadClear_Rank'].iloc[i]*0.10)*100)
s2015.head()

/home/obafemi/.local/lib/python3.8/site-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

,Unnamed: 0,Player,Season,Born,Age,Squad,Nation,Previous Market Value,Market Value,Position,...,ABL,OVR(%),OVR,goals_Rank,passes_Rank,HeadClear_Rank,Blocks_Rank,HeadGoal_Rank,Interceptions_Rank,tackles_Rank
941,0,Aaron Cresswell,2018-2019,1989,28,West Ham United,England,13200000,9900000,DF,...,18,24.6,34.0,0.273381,0.417266,0.302158,0.366906,0.402878,0.323741,0.330935
945,4,Aaron Wan-Bissaka,2018-2019,1997,21,Crystal Palace,England,900000,31500000,DF,...,30,36.2,75.0,0.273381,0.640288,0.737410,0.751799,0.402878,1.000000,0.992806
947,6,Adam Masina,2018-2019,1994,24,Watford,Italy,6300000,6300000,DF,...,15,11.8,24.0,0.273381,0.100719,0.266187,0.158273,0.402878,0.179856,0.345324
948,7,Adam Smith,2018-2019,1991,27,AFC Bournemouth,England,4500000,6300000,DF,...,31,26.4,47.0,0.273381,0.489209,0.456835,0.366906,0.402878,0.525180,0.651079
954,13,Adrian Mariappa,2018-2019,1986,31,Watford,Jamaica,1350000,2700000,DF,...,58,26.7,49.0,0.273381,0.503597,0.683453,0.708633,0.402878,0.381295,0.460432

In [210]:
s2015.sort_values('OVR',ascending=True).head(20)

,Unnamed: 0,Player,Season,Born,Age,Squad,Nation,Previous Market Value,Market Value,Position,...,ABL,OVR(%),OVR,goals_Rank,passes_Rank,HeadClear_Rank,Blocks_Rank,HeadGoal_Rank,Interceptions_Rank,tackles_Rank
1118,177,Emerson,2018-2019,1994,24,Chelsea,Italy,18000000,13500000,DF,...,9,11.9,9.0,0.273381,0.100719,0.007194,0.017986,0.402878,0.021583,0.046763
1113,172,Diego Rico,2018-2019,1993,25,AFC Bournemouth,Spain,2250000,8100000,DF,...,9,7.1,11.0,0.273381,0.014388,0.025180,0.053957,0.402878,0.136691,0.046763
1363,422,Rúben Vinagre,2018-2019,1999,19,Wolves,Portugal,1800000,6300000,DF,...,17,6.8,11.0,0.273381,0.021583,0.025180,0.053957,0.402878,0.136691,0.046763
1119,178,Eric Bailly,2018-2019,1994,24,Manchester United,Cote D'Ivoire,31500000,22500000,DF,...,4,7.4,14.0,0.273381,0.035971,0.082734,0.158273,0.402878,0.111511,0.075540
1416,475,Stephan Lichtsteiner,2018-2019,1984,34,Arsenal,Switzerland,1350000,900000,DF,...,20,13.2,15.0,0.273381,0.129496,0.176259,0.158273,0.402878,0.039568,0.075540
1114,173,Diogo Dalot,2018-2019,1999,19,Manchester United,Portugal,13500000,18000000,DF,...,5,11.9,15.0,0.273381,0.079137,0.118705,0.053957,0.402878,0.057554,0.223022
1014,73,Benjamin Mendy,2018-2019,1994,24,Manchester City,France,36000000,31500000,DF,...,22,19.1,16.0,0.273381,0.273381,0.082734,0.158273,0.402878,0.057554,0.111511
1430,489,Timothy Fosu-Mensah,2018-2019,1998,20,Fulham,Netherlands,6300000,6300000,DF,...,13,10.8,17.0,0.273381,0.071942,0.050360,0.237410,0.402878,0.093525,0.143885
1220,279,Jonjoe Kenny,2018-2019,1997,21,Everton,England,4500000,4500000,DF,...,11,11.5,17.0,0.273381,0.086331,0.147482,0.053957,0.402878,0.179856,0.187050
1023,82,Bruno,2018-2019,1980,38,Brighton and Hove Albion,Spain,750000,100000,DF,...,16,14.2,17.0,0.273381,0.151079,0.118705,0.053957,0.402878,0.075540,0.258993
1052,111,Chris Mepham,2018-2019,1997,20,AFC Bournemouth,Wales,7200000,11700000,DF,...,19,10.8,18.0,0.273381,0.064748,0.338129,0.237410,0.402878,0.136691,0.014388
1197,256,Javier Manquillo,2018-2019,1994,24,Newcastle United,Spain,5000000,5000000,DF,...,20,9.0,19.0,0.273381,0.050360,0.208633,0.017986,0.402878,0.179856,0.309353
1085,144,Danilo,2018-2019,1991,27,Manchester City,Brazil,18000000,18000000,DF,...,14,23.2,21.0,0.658273,0.363309,0.082734,0.007194,0.402878,0.158273,0.169065
1437,496,Tommy Smith,2018-2019,1992,26,Huddersfield Town,England,2700000,2700000,DF,...,14,13.5,21.0,0.273381,0.136691,0.014388,0.158273,0.402878,0.197842,0.291367
1369,428,Rob Holding,2018-2019,1995,22,Arsenal,England,6300000,10800000,DF,...,9,17.7,21.0,0.273381,0.244604,0.241007,0.366906,0.402878,0.093525,0.025180
1033,92,Callum Paterson,2018-2019,1994,23,Cardiff City,Scotland,3150000,4500000,DF,...,217,17.1,22.0,0.964029,0.179856,0.176259,0.053957,0.402878,0.021583,0.179856
1236,295,Joseph Gomez,2018-2019,1997,21,Liverpool,England,19800000,31500000,DF,...,19,23.5,22.0,0.273381,0.402878,0.197842,0.237410,0.402878,0.136691,0.136691
1388,447,Scott Dann,2018-2019,1987,31,Crystal Palace,England,4500000,3600000,DF,...,16,6.3,23.0,0.273381,0.007194,0.338129,0.633094,0.402878,0.007194,0.007194
1218,277,Jon Gorenc Stankovic,2018-2019,1996,22,Huddersfield Town,Slovenia,450000,1350000,DF,...,16,7.3,23.0,0.273381,0.028777,0.050360,0.474820,0.402878,0.039568,0.291367
1329,388,Nathaniel Clyne,2018-2019,1991,27,AFC Bournemouth,England,18000000,10800000,DF,...,12,14.6,24.0,0.273381,0.158273,0.035971,0.104317,0.402878,0.197842,0.503597