In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
sns.set_style("darkgrid")
plt.style.use('fivethirtyeight')  
plt.rcParams['figure.figsize'] = 9,5
import warnings
warnings.filterwarnings('ignore')

In [2]:
strikers = pd.read_csv("strikers.csv")

In [3]:
strikers.head()

,Unnamed: 0,Player,Season,Born,Age,Squad,Nation,Previous Market Value,Market Value,Position,...,Blocks,Interceptions,Fouls,Last man,Tackles,ELG,OwnGoal,Clears,ABW,ABL
0,0,Éder,2015-2016,1987,27,Swansea City,Portugal,5500000,4500000,FW,...,0,0,11,0,4,0,0,7,9,20
1,1,Álvaro Morata,2017-2018,1992,25,Chelsea,Spain,44000000,58500000,FW,...,4,6,41,0,13,0,0,20,54,59
2,2,Álvaro Morata,2018-2019,1992,25,Chelsea,Spain,58500000,45000000,FW,...,1,0,19,0,8,0,0,6,18,28
3,3,Álvaro Negredo,2016-2017,1985,30,Middlesbrough,Spain,8250000,6750000,FW,...,3,10,45,0,18,0,0,65,175,177
4,23,Abel Hernández,2016-2017,1990,25,Hull City,Uruguay,7200000,7200000,FW,...,0,3,19,0,8,0,0,3,22,50

In [5]:
strikers.columns

Index(['Unnamed: 0', 'Player', 'Season', 'Born ', 'Age', 'Squad', 'Nation',
       'Previous Market Value', 'Market Value', 'Position', 'App', 'Minutes',
       'Goals', 'Passes', 'Assists', 'Yellow', 'Red', 'SubOn', 'SubOff',
       'Shots', 'SOT', 'HitPost ', 'HeadClear', 'HeadGoal', 'PKScored',
       'FKGoal', 'Offsides', 'ThrBall', 'Misses', 'Corners', 'Crosses',
       'Blocks', 'Interceptions', 'Fouls', 'Last man ', 'Tackles', 'ELG',
       'OwnGoal', 'Clears', 'ABW', 'ABL'],
      dtype='object')

In [17]:
series =strikers[strikers.columns[1:]].corr()['Market Value'][:]

In [20]:
series.where(series > 0.5).to_frame().dropna()

                       Market Value
Previous Market Value      0.920644
Market Value               1.000000
Goals                      0.657682
Passes                     0.503351
Assists                    0.577943
Shots                      0.607226
SOT                        0.666845
Misses                     0.585659

In [ ]:
New_colum = 0.65*number_goals + 0.5*passes + 0.58*Assists + 0.60*shots +0.66*SOT + 0.58*Misses

In [1]:
b =set()
a = ['femi', 'orange', 'boy','boy','orange']
for i in a:
    b.add(i)
for i in b:
    print(i)

orange
boy
femi